name: lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  vet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: run vet
        run: go vet
