name: tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: go test -race ./... -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23.x'
      with:
        file: ./coverage.txt
        flags: unittests
        env_vars: OS,GO
        name: codecov
        fail_ci_if_error: true
